// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NesrinBookStore.Data.Contexts;

#nullable disable

namespace NesrinBookStore.Data.Migrations
{
    [DbContext(typeof(NesrinDbContext))]
    [Migration("20221031130912_Validation")]
    partial class Validation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("NesrinBooks.API.DataAccess.Entities.Books", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("BookId");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Price")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.HasKey("Id");

                    b.ToTable("books");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c9d4c053-49b6-410c-bc78-2d54a9991870"),
                            Author = "Kel Nyuport",
                            Description = "Tavsiya etiladi.",
                            Name = "Diqqat",
                            Price = "40 000",
                            Rating = "4"
                        },
                        new
                        {
                            Id = new Guid("f50fb0cb-cfe7-4649-af66-8178ad69230a"),
                            Author = "Ahadquli XolMuhammad O'g'li",
                            Description = "Albatt tavsiya etiladi.",
                            Name = "Savdogarlar Ustozi",
                            Price = "30 000",
                            Rating = "5"
                        },
                        new
                        {
                            Id = new Guid("4fdb4eec-1015-41a2-aab2-cf765fedb868"),
                            Author = "Robert Kiyosaki",
                            Description = "Tavsiya etilmaydi.",
                            Name = "Boy ota kambag'al ota",
                            Price = "40 000",
                            Rating = "2"
                        },
                        new
                        {
                            Id = new Guid("9126aea5-cfa3-4e45-92da-be5ca57d3afe"),
                            Author = "Nomalum",
                            Description = "Tavsiya etiladi.",
                            Name = "Qalb iffati",
                            Price = "40 000",
                            Rating = "4"
                        },
                        new
                        {
                            Id = new Guid("71da79e2-fecd-4e4b-bdca-40e7d6b1f421"),
                            Author = "Muhammad Yusuf Muhammad Sodiq",
                            Description = "Albatta tavsiya etiladi.",
                            Name = "Baxtiyor Oila",
                            Price = "60 000",
                            Rating = "5"
                        },
                        new
                        {
                            Id = new Guid("7178347d-1cc5-4b67-80e2-13e27f295c7a"),
                            Author = "Muhammad Yusuf Muhammad Sodiq",
                            Description = "Albatt tavsiya etiladi.",
                            Name = "Ijyimoiy odoblar",
                            Price = "50 000",
                            Rating = "5"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
